# Generated by Django 4.1.5 on 2023-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_addmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='umodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
