# Generated by Django 4.1.5 on 2023-01-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0004_umodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='umodel',
        ),
    ]
