# Generated by Django 4.1.5 on 2023-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0008_userprofilemod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofilemod',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
