# Generated by Django 4.1.5 on 2023-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0012_appliedusersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewapplymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('jtitle', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='capp/static')),
            ],
        ),
    ]
