# Generated by Django 4.1.5 on 2023-01-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0013_viewapplymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appliedusersmodel',
        ),
    ]
