# Generated by Django 4.1.5 on 2023-01-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0014_delete_appliedusersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewapplymodel',
        ),
    ]
