# Generated by Django 4.1.5 on 2023-02-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0015_delete_viewapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
