# Generated by Django 4.1.5 on 2023-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0016_userprofilemodel_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('jtitle', models.CharField(max_length=25)),
                ('jtype', models.CharField(max_length=25)),
                ('wtype', models.CharField(max_length=25)),
                ('exp', models.CharField(max_length=25)),
                ('qualify', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='wishlistmodel',
        ),
    ]
